In [33]:
import numpy as np
import pandas as pd
from scipy.stats import norm
import copy



In [72]:
f= open("parameters.txt","r")
n= int(f.readline())
print(n)
transitionMatrix= np.empty([n,n])
for  i in range(n):
    str = f.readline()
    l=[np.double(p) for p in str.split()]
    transitionMatrix[i] = l
# transitionMatrix= np.asmatrix(transitionMatrix)

Mean= f.readline()
print( "mean is ",Mean)
Mean=[np.double(p) for p in Mean.split()]
Variance = f.readline()
Variance=[np.double(p) for p in Variance.split()]
transitionMatrix

2
mean is  200	100



array([[0.7, 0.3],
       [0.1, 0.9]])

In [74]:
def initialEstimator(mat):
    mat1= copy.deepcopy(mat)
    print(mat1)
    # print(mat2)
    # print(x)
    for i in range(20):
    # while not(np.isclose(mat1, mat1[0]).all()):
        mat1= mat1 @ mat1
    # print(np.isclose(mat1, mat1[0]).all())
    print(mat1)
    return mat1[0]


ans= initialEstimator(transitionMatrix)
ans =np.asarray(ans)
temp = np.arange(3)

ans


[[0.7 0.3]
 [0.1 0.9]]
[[0.25 0.75]
 [0.25 0.75]]


array([0.25, 0.75])

In [76]:
dataFile = open("data.txt","r")
data= np.double(dataFile.readlines())

length = len(data)
emissionMatrix=np.empty((n,length))
for i in range(n):
    emissionMatrix[i]= norm(Mean[i],np.sqrt(Variance[i])).pdf(data)

# emissionMatrix=np.asmatrix(emissionMatrix).T
emissionMatrix.shape


(1000, 2)